distributable:
  url: https://github.com/emilpriver/geni/archive/refs/tags/v0.0.3.tar.gz
  strip-components: 1

provides:
  - bin/geni

versions:
  - 2023.12.29
  - 2023.12.27

build:
  dependencies:
    rust-lang.org: ">=1.65"
    rust-lang.org/cargo: "*"
  script: cargo install --locked --path . --root {{prefix}}

test:
  script:
    - test "$(geni --version)" = "geni 0.0.3"
